"""initial schema -- rule_sets, rules, decisions, manual_overrides,
escalation_policies, escalation_events, audit_log, request_log

Hand-written rather than autogenerated: this environment has no live
Postgres to diff against, and autogenerate against a SQLite stand-in would
emit SQLite-flavored types (plain JSON/String) instead of the Postgres-
native JSONB/UUID/ARRAY types this schema actually wants in production.
Mirrors app/infrastructure/db/models.py column-for-column; if they drift,
this migration is the one that's wrong.

Revision ID: 0001
Revises:
Create Date: 2026-07-24
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS pgcrypto')

    op.create_table(
        "rule_sets",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lock_version", sa.Integer, nullable=False, server_default="1"),
        sa.Column("name", sa.String(100), nullable=False),
        sa.Column("version", sa.Integer, nullable=False),
        sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        sa.Column("region", sa.String(50), nullable=True),
        sa.Column("tenant_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("parent_version_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("rule_sets.id"), nullable=True),
        sa.Column("created_by", sa.String(100), nullable=False, server_default="system"),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.UniqueConstraint("name", "version", "region", "tenant_id", name="ux_rule_set_version"),
    )
    op.create_index("idx_rule_sets_active_lookup", "rule_sets", ["name", "region", "tenant_id", "status"])

    op.create_table(
        "rules",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lock_version", sa.Integer, nullable=False, server_default="1"),
        sa.Column("rule_set_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("rule_sets.id", ondelete="CASCADE"), nullable=False),
        sa.Column("rule_code", sa.String(20), nullable=False),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("description", sa.Text, nullable=True),
        sa.Column("priority_weight", sa.Integer, nullable=False),
        sa.Column("severity_band", sa.String(20), nullable=True),
        sa.Column("contribution_score", sa.Integer, nullable=True),
        sa.Column("family", sa.String(40), nullable=False),
        sa.Column("family_order", sa.Integer, nullable=False),
        sa.Column("conditions", postgresql.JSONB, nullable=False),
        sa.Column("exceptions", postgresql.JSONB, nullable=True),
        sa.Column("conflict_group", sa.String(50), nullable=True),
        sa.Column("conflicts_with", postgresql.ARRAY(sa.String), nullable=False, server_default="{}"),
        sa.Column("is_suppressor", sa.Boolean, nullable=False, server_default=sa.false()),
        sa.Column("non_suppressible", sa.Boolean, nullable=False, server_default=sa.false()),
        sa.Column("cooldown_minutes", sa.Integer, nullable=False, server_default="0"),
        sa.Column("actions", postgresql.JSONB, nullable=False),
        sa.Column("mitigations", postgresql.JSONB, nullable=False, server_default="{}"),
        sa.Column("sequencing", postgresql.JSONB, nullable=True),
        sa.Column("sla_target", sa.String(30), nullable=True),
        sa.Column("region", sa.String(50), nullable=True),
        sa.Column("tenant_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("rule_status", sa.String(20), nullable=False, server_default="ACTIVE"),
        sa.Column("enabled", sa.Boolean, nullable=False, server_default=sa.true()),
        sa.Column("created_by", sa.String(100), nullable=False, server_default="system"),
        sa.Column("approved_by", sa.String(100), nullable=True),
        sa.UniqueConstraint("rule_set_id", "rule_code", name="ux_rule_code_per_set"),
    )
    op.create_index("idx_rules_conditions_gin", "rules", ["conditions"], postgresql_using="gin")
    op.create_index("idx_rules_actions_gin", "rules", ["actions"], postgresql_using="gin")
    op.create_index("idx_rules_active", "rules", ["rule_set_id", "enabled", "rule_status"])
    op.create_index("idx_rules_family_order", "rules", ["rule_set_id", "family_order", "priority_weight"])

    op.create_table(
        "decisions",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("incident_id", sa.String(50), nullable=False),
        sa.Column("rule_set_name", sa.String(100), nullable=True),
        sa.Column("rule_set_version", sa.Integer, nullable=True),
        sa.Column("priority", sa.String(20), nullable=True),
        sa.Column("risk_score", sa.Integer, nullable=True),
        sa.Column("risk_band", sa.String(20), nullable=True),
        sa.Column("decision", postgresql.JSONB, nullable=False),
        sa.Column("mitigations", postgresql.JSONB, nullable=False, server_default="{}"),
        sa.Column("execution_plan", postgresql.JSONB, nullable=False, server_default="[]"),
        sa.Column("matched_rules", postgresql.JSONB, nullable=False, server_default="[]"),
        sa.Column("rejected_rules", postgresql.JSONB, nullable=False, server_default="[]"),
        sa.Column("suppressed_rules", postgresql.JSONB, nullable=False, server_default="[]"),
        sa.Column("compliance_constraints", postgresql.JSONB, nullable=False, server_default="[]"),
        sa.Column("confidence_score", sa.Numeric(5, 2), nullable=True),
        sa.Column("degraded_context", sa.Boolean, nullable=False, server_default=sa.false()),
        sa.Column("explanation", sa.Text, nullable=False, server_default=""),
        sa.Column("engine_version", sa.String(20), nullable=False, server_default="0.1.0"),
        sa.Column("resolved", sa.Boolean, nullable=False, server_default=sa.false()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )
    op.create_index("idx_decisions_incident", "decisions", ["incident_id"])

    op.create_table(
        "manual_overrides",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("decision_id", sa.String(50), nullable=False),
        sa.Column("operator", sa.String(100), nullable=False),
        sa.Column("original_decision", postgresql.JSONB, nullable=False),
        sa.Column("override_decision", postgresql.JSONB, nullable=False),
        sa.Column("reason", sa.Text, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )

    op.create_table(
        "escalation_policies",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("severity_band", sa.String(20), nullable=False, unique=True),
        sa.Column("levels", postgresql.JSONB, nullable=False),
    )

    op.create_table(
        "escalation_events",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("decision_id", sa.String(50), nullable=False),
        sa.Column("level", sa.String(30), nullable=False),
        sa.Column("triggered_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acknowledged_by", sa.String(100), nullable=True),
    )
    op.create_index("idx_escalation_events_decision", "escalation_events", ["decision_id", "triggered_at"])

    op.create_table(
        "audit_log",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("entity_type", sa.String(50), nullable=False),
        sa.Column("entity_id", sa.String(100), nullable=False),
        sa.Column("action", sa.String(50), nullable=False),
        sa.Column("actor", sa.String(100), nullable=False),
        sa.Column("before", postgresql.JSONB, nullable=True),
        sa.Column("after", postgresql.JSONB, nullable=True),
        sa.Column("ip_address", sa.String(64), nullable=True),
        sa.Column("request_id", sa.String(64), nullable=True),
        sa.Column("correlation_id", sa.String(64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )
    op.create_index("idx_audit_entity", "audit_log", ["entity_type", "entity_id", "created_at"])

    op.create_table(
        "request_log",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("method", sa.String(10), nullable=False),
        sa.Column("path", sa.String(255), nullable=False),
        sa.Column("status_code", sa.Integer, nullable=False),
        sa.Column("duration_ms", sa.Numeric(10, 2), nullable=False),
        sa.Column("request_id", sa.String(64), nullable=False),
        sa.Column("correlation_id", sa.String(64), nullable=True),
        sa.Column("ip_address", sa.String(64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )
    op.create_index("idx_request_log_request_id", "request_log", ["request_id"])


def downgrade() -> None:
    op.drop_table("request_log")
    op.drop_table("audit_log")
    op.drop_table("escalation_events")
    op.drop_table("escalation_policies")
    op.drop_table("manual_overrides")
    op.drop_table("decisions")
    op.drop_table("rules")
    op.drop_table("rule_sets")
